# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  openheritage:
    decidim.test
    labs.openheritage.eu
    ohpraga.pl
    co-roma.openheritage.eu
    hswsunderland.openheritage.eu
    praedikow.openheritage.eu
    lisboa.openheritage.eu
    pomaz.openheritage.eu
  openstreetmaps:
    ohpraga.pl
  matomo:
    id: 2
    url: https://analytics.platoniq.net/
    tenants:
      decidim.test: -1
      ohpraga.pl: 5
      co-roma.openheritage.eu: 6
      hswsunderland.openheritage.eu: 7
      praedikow.openheritage.eu: 8
      lisboa.openheritage.eu: 9
      pomaz.openheritage.eu: 10
  # provisional hacks for surveys to enable time-tracking
  timetracker:
    components: [ 189 ]
  menu:
    localhost:
      blog:
        key: decidim.components.blogs.name
        url: /processes/support/f/121/
        position: 4
    labs.openheritage.eu:
      blog:
        key: decidim.components.blogs.name
        url: /processes/support/f/121/
        position: 4
  rack_attack_skip: <%= ENV["RACK_ATTACK_APIKEY"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  omniauth:
    facebook:
      # It must be a boolean. Remember ENV variables doesn't support booleans.
      enabled: true
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    twitter:
      enabled: false
      api_key: <%= ENV["OMNIAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OMNIAUTH_TWITTER_API_SECRET"] %>
    google_oauth2:
      enabled: true
      client_id: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] %>
  geocoder:
    here_app_id: <%= ENV["GEOCODER_LOOKUP_APP_ID"] %>
    here_app_code: <%= ENV["GEOCODER_LOOKUP_APP_CODE"] %>
    here_api_key: <%= ENV["GEOCODER_LOOKUP_API_KEY"] %>
  etherpad:
    server: <%= ENV["ETHERPAD_SERVER"] %>
    api_key: <%= ENV["ETHERPAD_API_KEY"] %>
    api_version: "1.2.8"

development:
  <<: *default
  secret_key_base: 0c814430014f3ae4935079a87a5fd435959be5c1ef13c50548ab3522179e4fcda664337ae342965a673239dc30c3a6d2a501289b4037534c77c3105c800192d2
  timetracker:
    components: [ 5 ]
  omniauth:
    developer:
      enabled: true

test:
  <<: *default
  geocoder:
    here_api_key: test_app_id
  secret_key_base: a0d11d90c32038fde01ec1ad27460cd88788c2de7b12eb0f81aa594d417226c211802589977f690f2ddea4f77fedc1257f6d873e105a686dae4b978aebb2c56f
  omniauth:
    facebook:
      enabled: true
    twitter:
      enabled: true
    google_oauth2:
      enabled: true

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: &production
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_port: "587"
  smtp_starttls_auto: true
  smtp_authentication: "plain"

staging:
  <<: *production